In [2]:
import pandas as pd

# We'll read sheets one by one to avoid memory issues
combined_df_parts = []

for file_path in [
    '/Users/henrychiu/Documents/fuel check data/2022/combined_fuel_price_history_2022_cleaned.csv',
    '/Users/henrychiu/Documents/fuel check data/2023/combined_fuel_price_history_2023_cleaned.csv',
    '/Users/henrychiu/Documents/fuel check data/2024/combined_fuel_price_history_2024_cleaned.csv'
]:
    # Read only the first sheet to keep it consistent and fast
    df = pd.read_csv(file_path)
    combined_df_parts.append(df)

# Combine all dataframes
combined_df = pd.concat(combined_df_parts, ignore_index=True)

combined_df.head()

,ServiceStationName,Address,Suburb,Postcode,Brand,FuelCode,PriceUpdatedDate,Price
0,BP CAMDEN,"12 ARGYLE ST, CAMDEN NSW 2570",CAMDEN,2570.0,BP,E10,1/01/2022 12:02:04 AM,141.9
1,BP CAMDEN,"12 ARGYLE ST, CAMDEN NSW 2570",CAMDEN,2570.0,BP,U91,1/01/2022 12:02:04 AM,143.9
2,Caltex Woolworths Woolooware,"449 Captain Cook Drive, Woolooware NSW 2230",Woolooware,2230.0,Caltex Woolworths,U91,1/01/2022 12:04:40 AM,173.9
3,Caltex Woolworths Woolooware,"449 Captain Cook Drive, Woolooware NSW 2230",Woolooware,2230.0,Caltex Woolworths,P95,1/01/2022 12:04:40 AM,186.9
4,Caltex Woolworths Woolooware,"449 Captain Cook Drive, Woolooware NSW 2230",Woolooware,2230.0,Caltex Woolworths,E10,1/01/2022 12:04:40 AM,171.9

In [14]:
combined_df.head()

,ServiceStationName,Address,Suburb,Postcode,Brand,FuelCode,PriceUpdatedDate,Price
0,BP CAMDEN,"12 ARGYLE ST, CAMDEN NSW 2570",CAMDEN,2570.0,BP,E10,2022-01-01 00:02:04,141.9
1,BP CAMDEN,"12 ARGYLE ST, CAMDEN NSW 2570",CAMDEN,2570.0,BP,U91,2022-01-01 00:02:04,143.9
2,Caltex Woolworths Woolooware,"449 Captain Cook Drive, Woolooware NSW 2230",Woolooware,2230.0,Caltex Woolworths,U91,2022-01-01 00:04:40,173.9
3,Caltex Woolworths Woolooware,"449 Captain Cook Drive, Woolooware NSW 2230",Woolooware,2230.0,Caltex Woolworths,P95,2022-01-01 00:04:40,186.9
4,Caltex Woolworths Woolooware,"449 Captain Cook Drive, Woolooware NSW 2230",Woolooware,2230.0,Caltex Woolworths,E10,2022-01-01 00:04:40,171.9

In [11]:
# Convert 'PriceUpdatedDate' to datetime format
combined_df['PriceUpdatedDate'] = pd.to_datetime(combined_df['PriceUpdatedDate'], errors='coerce')
print(combined_df['PriceUpdatedDate'].dtypes)

/var/folders/56/9ccg46j54r99nc2y8w_2gvx00000gn/T/ipykernel_2264/1314246100.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  combined_df['PriceUpdatedDate'] = pd.to_datetime(combined_df['PriceUpdatedDate'], errors='coerce')

datetime64[ns]

In [15]:
# Save combined file
output_path = "/Users/henrychiu/Documents/fuel check project/fuel check data/combined_fuel_price_history_2022_2023_2024_cleaned_v2.csv"
combined_df.to_csv(output_path, index=False)